/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.informax.postgit;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author daniel.vazquez
 */
public class PanelDeveloper extends javax.swing.JPanel {

    private final long id;
    
    /**
     * Creates new form panelDeveloper
     */
    public PanelDeveloper(boolean selected, String urlImage, String name, long id) {
        initComponents();
        
        checkSelected.setSelected(selected);
        if(urlImage != null && !urlImage.isEmpty()) {
            try {
                Image carga = new ImageIcon(PanelDeveloper.class.getResource("images/loading.gif")).getImage();
                ImageIconAsync icon = new ImageIconAsync(new URL(urlImage), carga, lblImage);
                lblImage.setIcon(icon);
                icon.cargarImagen();
            }
            catch(MalformedURLException ex) { }
        }
        lblName.setText(name);
        this.id = id;
    }
    
    public boolean isSelected() {
        return checkSelected.isSelected();
    }
    
    public long getId() {
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkSelected = new javax.swing.JCheckBox();
        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setAlignmentX(0.0F);

        org.openide.awt.Mnemonics.setLocalizedText(checkSelected, org.openide.util.NbBundle.getMessage(PanelDeveloper.class, "PanelDeveloper.checkSelected.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblImage, org.openide.util.NbBundle.getMessage(PanelDeveloper.class, "PanelDeveloper.lblImage.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblName, org.openide.util.NbBundle.getMessage(PanelDeveloper.class, "PanelDeveloper.lblName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(checkSelected)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkSelected;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
